[package]
name = "poe_reflect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = "s"
overflow-checks = false
strip = true
lto = true
panic = "abort"
codegen-units = 1
